# .coderabbit.yaml
# Comprehensive CodeRabbit AI configuration for the 371 OS project.
# Documentation: https://docs.coderabbit.ai/configuration/yaml-template
version: 2.0

# Settings for how pull request summaries and walkthroughs are presented.
summaries:
  # Do not collapse the file-by-file walkthrough by default, as it's very useful for our complex project.
  collapse_walkthrough: false
  # Ensure a high-level summary is always generated.
  high_level_summary: true
  # Adds a fun, poetic summary of the PR changes.
  poem: true

# Instructions for automatically generating a PR title based on conventional commits.
auto_title:
  instructions: >
    Generate a pull request title using the conventional commit format: `<type>(<scope>): <subject>`.
    The <type> should be one of: feat, fix, docs, style, refactor, test, chore.
    The <scope> should be the primary package or area affected (e.g., 'phase-4', 'enhanced-intelligence', 'security').

# Instructions for automatically labeling the PR based on file paths and content.
auto_label:
  instructions: >
    Analyze the changed files and their content. Apply labels based on the following rules:
    - If changes are in 'packages/elizaos-plugins/enhanced-intelligence', add the 'phase-3' and 'agent-intelligence' labels.
    - If changes are related to performance optimization files like 'phase4-performance-optimizer.ts', add the 'phase-4' and 'performance' labels.
    - If changes modify '.github/workflows' or deployment scripts, add the 'ci-cd' label.
    - If changes involve '.env.example' or security configurations, add the 'security' label.
    - If only '.md' files are changed, add the 'documentation' label.

# Core settings for code review behavior.
reviews:
  # Automatically trigger reviews on new pull requests.
  auto_review:
    enabled: true
    # Do not review pull requests while they are still drafts.
    drafts: false
  
  # Set the review style. "chill" is a good balance between thoroughness and avoiding excessive nitpicking.
  profile: "chill"
  
  # Paths to exclude from line-by-line reviews to reduce noise and save tokens.
  # CodeRabbit will still use these files for overall context.
  path_filters:
    - '!**/dist/**'
    - '!**/node_modules/**'
    - '!**/*.md'
    - '!package-lock.json'
    - '!bun.lockb'
    - '!.nx/cache/**'

# Settings for the chat functionality within PR comments.
chat:
  # Allow CodeRabbit to automatically reply to mentions and questions.
  auto_reply: true
