version: "3.9"

services:
  app:
    build: .
    container_name: task-manager-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start

  test:
    build: .
    container_name: task-manager-tests
    depends_on:
      - app
    environment:
      - NODE_ENV=test
    command: npm test
